config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [ :new, :create, :destroy ]
  
  resources :subs, except: :destroy
  resources :posts, except: [ :index, :destroy ]
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :sub, :author, presence: true
  
  belongs_to(
    :sub,
    class_name: "Sub",
    foreign_key: :sub_id,
    primary_key: :id
  )
  
  belongs_to(
    :author,
    class_name: "User", 
    foreign_key: :author_id,
    primary_key: :id
  )
  
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true
  
  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id
  )
  
  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :sub_id,
    primary_key: :id
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  after_initialize :ensure_session_token
  
  has_many(
    :subs,
    class_name: "Sub",
    foreign_key: :moderator_id,
    primary_key: :id
  )
  
  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def ensure_session_token
    self.session_token ||= generate_session_token
  end
  
  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end
  
  def generate_session_token
    SecureRandom::urlsafe_base64
  end
  
  def reset_session_token!
    # for signing out. 
    self.session_token = generate_session_token
    self.save!
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    return if logged_in?
    flash[:errors] ||= [] << "Must be logged in to create a sub."
    redirect_to subs_url unless logged_in?
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :require_user, except: :show
  # before_action :edit_privileges?, only: [ :edit, :update ]
  
  def new
    @post = Post.new
    render :new
  end
  
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      flash[:notices] = ["Post successfully made"]
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end
  
  def show
    @post = Post.find(params[:id])
    render :show
  end
  
  def edit
    @post = Post.find(params[:id])
    if edit_privileges?(@post)
      render :edit
    else
      # error message in flash.
      flash[:errors] = ["You're not authorized to edit this post."]
      # redirect. 
      redirect_to post_url(@post)
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if edit_privileges?(@post)
      if @post.update_attributes(post_params)
        flash[:notices] = ["Post successfully edited!"]
        redirect_to post_url(@post)
      else
        flash[:errors] = @post.errors.full_messages
        render :edit
      end
    else
      flash[:errors] = ["You're not authorized to edit this post."]
      redirect_to post_url(@post)
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id)
  end
  
  def edit_privileges?(post)
    current_user.id == post.author_id
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(
        params[:user][:username],
        params[:user][:password]
    )
    
    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash[:errors] = ["Incorrect login"]
      redirect_to new_session_url
    end
   
  end
  
  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to users_url
  end
  
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_user, only: [:new, :create, :edit, :update]
  
  def new
    @sub = Sub.new
    render :new
  end
  
  def create
    @sub = current_user.subs.new(sub_params)
    
    if @sub.save
      flash[:notices] ||= [] << "Sub \"#{ @sub.title }\" created. Success!"
      redirect_to subs_url
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  
  def show
    @sub = Sub.find(params[:id])
    render :show
  end
  
  def edit
    # moderator can edit title and description
    @sub = Sub.find(params[:id])
    render :edit
  end
  
  def update
    @sub = Sub.find(params[:id])
    
    if @sub.update_attributes(sub_params)
      flash[:notices] ||= [] << "Sub \"#{ @sub.title }\" edited!"
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
  
  def index
    @subs = Sub.all
    render :index
  end
  
  private
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def index
    @users = User.all
    render :index
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    token = '<input type="hidden" name="authenticity_token" value="'
    token += form_authenticity_token
    token += '">'
    token.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<!-- Notices --> 
<% unless flash[:notices].nil? %>
  <ul>
    <% flash[:notices].each do |notice| %>
      <li> <%= notice %> </li>
    <% end %>
  </ul>
<% end %>

<!-- Errors --> 
<% unless flash[:errors].nil? %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">
  
  <%= auth_token %>
  
  <label for="username">Username
    <input 
      type="text"
      name="user[username]"
      value="<%= user.username %>">
  </label>
  
  <label for="password">Password
    <input 
      type="password"
      name="user[password]">
  </label>
  
  <button>Submit</button>
  
  
</form>

app/views/layouts/_post_form.html.erb
<form action="<%= action %>" method="post">
  
  <%= auth_token %>
  
  <p><sup>*</sup> : Required Field</p>
  <input 
    type="hidden" 
    name="_method" 
    value="<%= method %>">
    
  <label for="post_title">Title<sup>*</sup></label>  
  <input 
    type="text" 
    label="post_title" 
    name="post[title]" 
    value="<%= post.title %>">
    
  <label for="post_url">URL</label>   
  <input 
    type="text" 
    label="post_url" 
    name="post[url]" 
    value="<%= post.url %>">
    
  <label for="post_content">Content</label>
  <textarea name="post[content]"><%= post.content %></textarea>
  <br>
  
  <label for="post_sub">Sub<sup>*</sup></label>
  <select name="post[sub_id]" id="sub">
    <option value=""></option>
    <% Sub.all.each do |sub| %>
      <option value="<%= sub.id %>" 
        <%= "selected" if @sub == sub %> >
        <%= sub.title %></option>
    <% end %>
  </select>
  <br>
  
  <button>Submit</button>

app/views/layouts/_session.html.erb
<% if logged_in? %>
  <p>Howdy <%= current_user.username %>!</p>
  <%= button_to "Log out", session_url, method: :delete %>
<% else %>
  <p>Not logged in</p>
  <%= link_to "Login", new_session_url, method: :get %> or 
  <%= link_to "Register", new_user_url, method: :get %>
<% end %>

app/views/layouts/_subs_form.html.erb
<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">
  
  <%= auth_token %>
  
  <label for="sub_title">Title
    <input 
      type="text"
      name="sub[title]"
      value="<%= sub.title %>">
  </label>
  
  <label for="sub_description">Description
    <textarea
      name="sub[description]"><%= sub.description %></textarea>
  </label>
  
  <button>Submit</button>
  
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", subs_url, method: :get %>  
<%= render "layouts/session" %>
<%= render "layouts/flash" %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h2>Edit <%= @post.title %>!</h2>

<%= render "layouts/post_form", action: post_url(@post), 
  method: :patch, post: @post %>

app/views/posts/new.html.erb
<h2>Make a new post!</h2>

<%= render "layouts/post_form", action: posts_url, 
  method: :post, post: @post %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<p>Post for Sub: <%= link_to @post.sub.title, sub_url(@post.sub) %></p>
<% unless @post.url.empty? %>
  <%= link_to "URL", @post.url, method: :get %>
<% end %>

<p>Posted by: <%= @post.author.username %></p>

<% unless @post.content.empty? %>
  <div class="content">
    <p>Content</p>
    <%= @post.content%>
  </div>
<% end %>

<br>
<% if @post.author == current_user %>
  <%= link_to "Edit Post", edit_post_url(@post), method: :get %>
<% end %>

app/views/subs/edit.html.erb
<h2>Edit the <%= @sub.title %> Sub</h2>

<%= render "layouts/subs_form", 
        action: sub_url(@sub), method: "patch", sub: @sub %>

app/views/subs/index.html.erb
<ul>
  <% @subs.each do |sub| %>
    <li> <%= link_to sub.title, sub_url(sub), method: :get %> </li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h2>Make a Sub</h2>

<%= render "layouts/subs_form", action: subs_url, method: "post", sub: @sub %>

app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<p><em><%= @sub.description %></em></p>

<p>Moderator is: <%= @sub.moderator.username %>.

<% if @sub.moderator == current_user %>
  Hey! That's you!
  Want to <%= link_to "edit sub", edit_sub_url(@sub), method: :get %>?
<% end %>
</p>

<ol>
<% @sub.posts.each do |post| %>
  <li><%= link_to post.title, post_url(post) %>, 
    posted by <%= post.author.username %> </li>
<% end %>
</ol>

<%= link_to "Add a post", new_post_url %>

app/views/users/index.html.erb
<h2>All the users!</h2>

<ul>
  <% @users.each do |user| %>
    <li>User: <%= user.username %></li>
  <% end%>
</ul>
      

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render "layouts/form", action: users_url, method: "post", user: @user %>